spring:
    application:
        name: MerchantService
    jpa:
        hibernate.ddl-auto: update
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnet=true
        username: admin
        password: 1993
    kafka:
        producer:
            bootstrap-servers: 127.0.0.1:9092
        consumer:
            group-id: passbook
        listener:
            concurrency: 4
server:
    port: 9527
logging:
    level.*: DEBUG
    file: merchantservice.log

